feat(#14): import gitlab stuff
python/cpython-devcontainers pull request #18
Opened 2024-10-10 22:14 UTC by JacobCoffee

Moves Gitlab files here

Partially resolves #14

2024-10-10 22:14 UTC, JacobCoffee commented on .github/workflows/ci-images.yml
Will need Gitlab publishing. Unsure how atm (never used gitlab)

Could maybe base off of https://github.com/docker/build-push-action/blob/4f58ea79222b3b9dc2c8bbdd6debcef730109a75/.github/workflows/.e2e-run.yml, https://github.com/docker/build-push-action/blob/4f58ea79222b3b9dc2c8bbdd6debcef730109a75/.github/workflows/e2e.yml#L43

2024-10-10 22:14 UTC, JacobCoffee commented on .github/workflows/ci-images.yml
> +#     - uses: actions/checkout@v4  # I dont think this is needed given git context defaults in build-push-action?
should verify

2024-10-10 22:15 UTC, JacobCoffee commented on cpython-ci/LICENSE.txt
Can this go away in favor of the top level MIT license?

2024-10-10 22:15 UTC, JacobCoffee commented on cpython-ci/README.md
> +[GitLab](https://gitlab.com/python-devs/ci-images/container_registry).
needs update for GH

2024-10-10 22:25 UTC, JacobCoffee commented
changing `get-pythons.sh` to `-j16` goes brrr
`[+] Building 372.5s (16/16) FINISHED`

2024-10-10 22:37 UTC, JacobCoffee commented on .github/workflows/ci-images.yml
> +    GITLAB_REGISTRY: ${{ secrets.GITLAB_REGISTRY }}
?

2024-10-11 06:18 UTC, corona10 commented
cc @warsaw

2024-10-11 06:19 UTC, corona10 requested changes
Would you like to update CODEOWENER file to be you, @warsaw and me?

2024-10-11 06:21 UTC, corona10 commented on .github/workflows/ci-images.yml
> +  release:
Oh let's separate the publish process from now on.
Just verify and test will be enough.

2024-10-11 06:23 UTC, corona10 commented on .github/workflows/ci-images.yml
> +    GITHUB_REGISTRY: ghcr.io
Please take a look at how we verify autoconf file at Github Action.
I wish to use similar approach at CI level.
https://github.com/python/cpython-devcontainers/blob/main/.github/workflows/ci.yml

2024-10-11 06:33 UTC, corona10 commented on cpython-ci/LICENSE.txt
Let's talk with @warsaw about this issue. :)

2024-10-11 06:35 UTC, corona10 commented on .github/workflows/ci-images.yml
Yeah, we will need it, but maybe through manual dispatch?   Let's discuss this separately.

2024-10-11 16:36 UTC, warsaw commented on .github/workflows/ci-images.yml
FWIW the docs on GL container registry are here: https://docs.gitlab.com/ee/user/packages/container_registry/index.html

I don't know how you'd upload images built on GitHub to this though.

2024-10-11 16:40 UTC, warsaw commented
> Would you like to update CODEOWENER file to be you, @warsaw and me?

Asking also for @maxking who is a core dev and also worked on the GitLab container stuff.

2024-10-11 16:44 UTC, warsaw commented on cpython-ci/LICENSE.txt
Apache is my default OSS license these because it's pretty unencumbered and non-controversial, plus it's one of the [PSF CLA incoming licenses](https://www.python.org/psf/contrib/contrib-form/).

2024-10-11 17:10 UTC, maxking commented
I don't mind helping out with container stuff since I maintain it for mailman anyway.

2025-05-29 18:36 UTC, brettcannon commented
What's the status of this PR?

2025-05-29 18:40 UTC, warsaw commented
> What's the status of this PR?

I have no time or interest in migrating it.  It's almost literally zero effort to keep running on GitLab.  Maybe the thing to do is to start with mirroring that repo here and having two places where the containers are uploaded (as long as they can be made bit-for-bit identical).   I think people are still relying on the GitLab images.

2025-08-27 17:42 UTC, brettcannon commented
@JacobCoffee did you want to keep this PR going or should we close it?

2025-09-02 15:28 UTC, JacobCoffee commented
@brettcannon we can close if we still want to keep things on gitlab, or i can continue on maybe at core dev sprints coming up if its something good i can work on? 

i don't really have a list of things to work on for the sprint yet so i'm grateful for any direction on that front

2025-09-02 18:40 UTC, brettcannon commented
> if its something good i can work on?

I'm sure you can corner @warsaw at the sprints and hash it out. 😉



> i don't really have a list of things to work on for the sprint yet so i'm grateful for any direction on that front

Let's see how my WASI presentation goes as that may lead to a slight tweak to the dev container if you're after stuff related to this repo.

2025-09-18 15:40 UTC, JacobCoffee commented
barry didn't want to sprint

2025-09-18 15:40 UTC, closed without merging